import {Pathname} from './pathname.js'
import {publish as pub} from './event-bus.js'

class DocFuConfig {
  constructor(source, sandbox) {
    // import.meta.url is a file:// URL, normalize handles it
    const modulePath = new Pathname(import.meta.url)
    this.#directory = modulePath.directory

    const pkgPath = this.directory.closest('package.json')
    if (!pkgPath) throw new Error(`Could not find package.json from ${this.directory}`)

    const pkgContents = pkgPath.read()
    this.#packageData = JSON.parse(pkgContents)
    this.#setSourceDirectory(source)
    this.#setSandboxDirectory(sandbox)
  }

  /**
   * DocFu package directory
   * @returns {Pathname}
   */
  get directory() {
    return this.#directory
  }

  /**
   * DocFu package.json data
   * @returns {Object}
   */
  get packageData() {
    return this.#packageData
  }

  /**
   * DocFu example config template path
   * @returns {Pathname}
   */
  get configTemplatePath() {
    return this.directory.join('docfu.example.yml')
  }

  /**
   * Gets master config path → [sandbox]/config.yml
   * Auto generated by: lib/cli/stage.js
   * @returns {Pathname|undefined}
   */
  get sandboxConfigPath() {
    return this.sandboxDirectory?.join('config.yml')
  }

  /**
   * Get build output path → [sandbox]/dist
   * Auto generated by: lib/cli/build.js
   * @returns {Pathname|undefined}
   */
  get sandboxDistDirectory() {
    return this.sandboxDirectory?.join('dist')
  }

  /**
   * Gets manifest path (metadata file) → [sandbox]/manifest.json
   * Auto generated by: lib/cli/stage.js
   * @returns {Pathname|undefined}
   */
  get sandboxManifestPath() {
    return this.sandboxDirectory?.join('manifest.json')
  }

  /**
   * Gets sandbox path
   * @returns {Pathname|undefined}
   */
  get sandboxDirectory() {
    return this.#sandboxDirectory
  }

  /**
   * Gets source path
   * @returns {Pathname|undefined}
   */
  get sourceDirectory() {
    return this.#sourceDirectory
  }

  /**
   * Gets workspace path (ephemeral starlight project) → [sandbox]/workspace
   * @returns {Pathname|undefined}
   */
  get sandboxWorkspaceDirectory() {
    return this.sandboxDirectory?.join('workspace')
  }

  /**
   * Sandbox directory and related paths
   * @returns {Object} Sandbox paths and metadata
   * @property {Pathname|undefined} directory - Sandbox root directory
   * @property {Object} config - Master config file metadata
   * @property {Pathname|undefined} config.path - Path to config.yml
   * @property {Object} dist - Build output metadata
   * @property {Pathname|undefined} dist.directory - Path to dist directory
   * @property {Object} manifest - Manifest file metadata
   * @property {Pathname|undefined} manifest.path - Path to manifest.json
   * @property {Object} workspace - Workspace metadata
   * @property {Pathname|undefined} workspace.directory - Path to workspace directory
   */
  get sandbox() {
    return {
      directory: this.sandboxDirectory,
      config: {path: this.sandboxConfigPath},
      dist: {directory: this.sandboxDistDirectory},
      manifest: {path: this.sandboxManifestPath},
      workspace: {directory: this.sandboxWorkspaceDirectory},
    }
  }

  /**
   * Source directory metadata
   * @returns {Object} Source paths
   * @property {Pathname|undefined} directory - User's markdown source directory
   */
  get source() {
    return {
      directory: this.sourceDirectory,
    }
  }

  #directory // DocFu package directory
  #packageData // DocFu package.json data
  #sandboxDirectory // DocFu's scratch disk (user configurable)
  #sourceDirectory // User's markdown directory (user configurable)

  /**
   * Sets sandbox path (default: [sourceDirectory]/.docfu)
   * @param {string} value
   * @returns {Pathname|undefined}
   */
  #setSandboxDirectory(value) {
    try {
      const path = value ? new Pathname(value) : this.sourceDirectory?.join('.docfu')

      if (path.isProtected) {
        pub('fail', {sandbox: `Invalid sandbox! ${value}`})
        process.exit(1)
      }

      this.#sandboxDirectory = path
      pub('done', {sandbox: this.sandboxDirectory})
      return this.sandboxDirectory
    } catch (err) {
      pub('fail', {sandbox: `Invalid sandbox! ${value}`})
      process.exit(1)
    }
  }

  /**
   * Sets source path
   * @param {string} value
   * @returns {Pathname}
   */
  #setSourceDirectory(value) {
    const path = new Pathname(value)

    if (!path.isDirectory) {
      pub('fail', {source: `Invalid source! Must be a directory. ${value}`})
      process.exit(1)
    }

    if (path.exists) {
      this.#sourceDirectory = path
      pub('done', {source: this.sourceDirectory})
      return this.sourceDirectory
    }

    pub('fail', {source: `Invalid source! ${value}`})
    process.exit(1)
  }
}

export {DocFuConfig}
