#!/usr/bin/env node

import {system} from '../lib/system.js'
import pkgmgr from '../lib/package-manager.js'

const exec = pkgmgr.getCommand('exec')
system(exec, 'markdown-toc -i --maxdepth 2 README.md')
system(
  exec,
  'prettier',
  '--log-level silent',
  '--write',
  '*.js',
  '*.json',
  '*.md',
  '*.mjs',
  './bin',
  './lib',
  './public/**/*.js',
  './scripts',
  './src',
  './test'
)
