#!/usr/bin/env node

import {dirname} from '../lib/file-system.js'
import {exec} from '../lib/process.js'
import {getPackageManagerCmd} from '../lib/package-manager.js'
import theme from '../lib/theme.js'

const __filename = dirname(import.meta.url)
console.info(theme.emphasis(`➜ ${__filename}`))
const cmd = getPackageManagerCmd('exec')
exec(cmd, 'markdown-toc -i --maxdepth 2 README.md')
exec(
  cmd,
  'prettier',
  '--log-level silent',
  '--write',
  '*.js',
  '*.json',
  '*.md',
  '*.mjs',
  './bin',
  './lib',
  './public/**/*.js',
  './scripts',
  './src',
  './test'
)
