#!/usr/bin/env node

import {dirname, join, realpath} from '../lib/file-system.js'
import {system} from '../lib/system.js'
import {loadPackageJSON} from '../lib/packages.js'
import pkgmgr from '../lib/package-manager.js'

system(pkgmgr.getCommand('pack'))
const filename = `docfu-${loadPackageJSON()?.version}.tgz`
const filepath = realpath(import.meta.url, filename)
system(pkgmgr.getCommand('install'), filepath)
