#!/usr/bin/env node

import {system} from '../lib/system.js'
import pkgmgr from '../lib/package-manager.js'

system(
  pkgmgr.getCommand('exec'),
  'prettier',
  '--check',
  '*.js',
  '*.json',
  '*.md',
  '*.mjs',
  './bin',
  './lib',
  './public/**/*.js',
  './scripts',
  './src',
  './test'
)
